from .models import Lyrics


class LyricsResource:
    """Resource manager for lyrics generation."""

    def __init__(self, client):
        """Initializes the LyricsResource with a client reference.

        Args:
            client (SunoClient): The parent client instance.
        """
        self.client = client

    def generate(
        self,
        prompt: str,
        callback_url: str | None = None,
        wait: bool = True,
        timeout: int = 120
    ) -> str | list[Lyrics]:
        """Generates lyrics based on a text prompt.

        Args:
            prompt (str): Text prompt describing the desired lyrics.
            callback_url (str, optional): Webhook URL for callback notification.
            wait (bool): If True, poll and wait for task completion. Defaults to True.
            timeout (int): Max time in seconds to wait for task completion. Defaults to 120.

        Returns:
            str | list[Lyrics]: A list of generated Lyrics objects if wait is True, otherwise the taskId as a string.
        """
        payload = {"prompt": prompt}
        if callback_url:
            payload["callBackUrl"] = callback_url

        res = self.client.post("/api/v1/lyrics", payload)
        task_id = res["data"]["taskId"]

        if not wait:
            return task_id

        task_data = self.client.wait_task(task_id, endpoint="/api/v1/lyrics/record-info", timeout=timeout)
        return Lyrics.from_task_data(task_data)

    def get(self, task_id: str) -> list[Lyrics]:
        """Retrieves the lyrics generated by a task.

        Args:
            task_id (str): The ID of the lyrics task.

        Returns:
            list[Lyrics]: A list of generated Lyrics objects.
        """
        task_data = self.client.get_task_info(task_id, endpoint="/api/v1/lyrics/record-info")
        return Lyrics.from_task_data(task_data)